import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import homeContent from '../content/homeContent';
import '../pages/Home.css';
import { useState } from 'react';
import Link from 'next/link';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  const [copied, setCopied] = useState(false);

  function handleCopyEmail() {
    const email = "alexzhaolixiuqi@gmail.com";
    navigator.clipboard.writeText(email)
      .then(() => {
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
      })
      .catch((err) => console.error("Copy failed:", err));
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js logo"
            width={180}
            height={38}
            priority
          />
          <ol>
            <li>
              Get started by editing <code>src/pages/index.tsx</code>.
            </li>
            <li>Save and see your changes instantly.</li>
          </ol>

          <div className={styles.ctas}>
            <a
              className={styles.primary}
              href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              <Image
                className={styles.logo}
                src="/vercel.svg"
                alt="Vercel logomark"
                width={20}
                height={20}
              />
              Deploy now
            </a>
            <a
              href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
              className={styles.secondary}
            >
              Read our docs
            </a>
          </div>
        </main>
        <footer className={styles.footer}>
          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Image
              aria-hidden
              src="/file.svg"
              alt="File icon"
              width={16}
              height={16}
            />
            Learn
          </a>
          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Image
              aria-hidden
              src="/window.svg"
              alt="Window icon"
              width={16}
              height={16}
            />
            Examples
          </a>
          <a
            href="https://nextjs.org?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Image
              aria-hidden
              src="/globe.svg"
              alt="Globe icon"
              width={16}
              height={16}
            />
            Go to nextjs.org →
          </a>
        </footer>
      </div>
      <div className="home">
        <section className="hero">
          <h1>{homeContent.hero.heading}</h1>
          <p>{homeContent.hero.subheading}</p>
        </section>

        <section className="about">
          <h2>
            <Link href="/about">{homeContent.about.heading}</Link>
          </h2>
          <div>
            {homeContent.about.content.map((line, index) => (
              <p key={index}>{line}</p>
            ))}
          </div>
        </section>

        <section className="skills">
          <h2>
            <Link href="/projects">{homeContent.skills.heading}</Link>
          </h2>
          <div className="skill-list">
            {[
              { name: 'Java', level: 80 },
              { name: 'C', level: 65 },
              { name: 'C++', level: 90 },
              { name: 'Python', level: 70},
              { name: 'JavaScript', level: 40 },
              { name: 'FPGA programming', level: 30 },
              { name: 'embedded system development', level: 90 },
              { name: 'React', level: 30 },
            ].map((skill, index) => (
              <div className="skill-item" key={index}>
                <span className="skill-name">{skill.name}</span>
                <div className="skill-bar">
                  <div className="skill-fill" style={{ width: `${skill.level}%` }}></div>
                </div>
              </div>
            ))}
          </div>
        </section>

        <section className="contact">
          <h2>
            <Link href="/contacts">{homeContent.contact.heading}</Link>
          </h2>
          <p>
            Email: <span id="email">alexzhaolixiuqi@gmail.com</span>
            <button onClick={handleCopyEmail} className="copy-btn">Copy</button>
            {copied && <span className="copied-message">✔ Copied!</span>}
          </p>
          <p className="social-links">
            <a href="https://www.linkedin.com/in/zhao-lixiuqi-73420926b" target="_blank" rel="noopener noreferrer" title="HIRE MEEEEEE">LinkedIn</a> |
            <a href="https://www.instagram.com/alex_go_sleep?igsh=MWJsZXlzbTg1bWV6cQ==" target="_blank" rel="noopener noreferrer" title="Follow me on Instagram?"> Instagram</a> |
            <a href="https://youtube.com/@alexgosleep-v9i?si=OdaBSALU5vuD5PBv" target="_blank" rel="noopener noreferrer" title="Subscribe to my channel please"> YouTube</a> |
            <a href="https://b23.tv/2sfFe5M" target="_blank" rel="noopener noreferrer" title="Bilibili is a Chinese video platform"> Bilibili</a>
          </p>
        </section>
      </div>
    </>
  );
}
